---
apiVersion: v1
kind: Namespace
metadata:
  name: kubent-exporter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubent-exporter
  namespace: kubent-exporter
  labels:
    app: kubent-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubent-exporter
  template:
    metadata:
      labels:
        app: kubent-exporter
    spec:
      containers:
        - name: kubent-exporter
          image: ghcr.io/isugimpy/kubent_exporter:0.0.3
          ports:
            - containerPort: 8000
              name: exporterport
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubent-exporter
  namespace: kubent-exporter
spec:
  selector:
    matchLabels:
      app: kubent-exporter
  podMetricsEndpoints:
    - port: exporterport
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubent-exporter
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubent-exporter
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubent-exporter
roleRef:
  kind: ClusterRole
  name: kubent-exporter
  apiGroup: rbac.authorization.k8s.io
